;;;; m3.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(scheme#eval '(import-syntax scheme m2))
(##sys#register-compiled-module
  'm3
  'm3
  (scheme#list)
  '()
  (scheme#list (scheme#cons 's3 (syntax-rules () ((_) (s2)))))
  (scheme#list))

;; END OF FILE
