;;;; reexport-m4.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(scheme#eval
  '(import-syntax scheme chicken.base chicken.module reexport-m3 reexport-m3))
(##sys#register-compiled-module
  'reexport-m4
  'reexport-m4
  (scheme#list '(bar . reexport-m3#bar))
  '()
  (scheme#list
    (scheme#cons 'baz (ir-macro-transformer (lambda (e i c) `(foo))))
    'foo
    'foo)
  (scheme#list))

;; END OF FILE
