;;;; reexport-m1.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'reexport-m1
  'reexport-m1
  (scheme#list)
  '((u8vector . srfi-4#u8vector))
  (scheme#list)
  (scheme#list))

;; END OF FILE
