;;;; reexport-m3.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(scheme#eval '(import-syntax scheme chicken.base))
(##sys#register-compiled-module
  'reexport-m3
  'reexport-m3
  (scheme#list '(bar . reexport-m3#bar))
  '()
  (scheme#list
    (scheme#cons 'foo (ir-macro-transformer (lambda (e i c) `(bar)))))
  (scheme#list))

;; END OF FILE
