;;;; reexport-m6.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(scheme#eval '(import-syntax chicken.module (prefix reexport-m5 #:f)))
(##sys#register-compiled-module
  'reexport-m6
  'reexport-m6
  (scheme#list)
  '()
  (scheme#list 'f:s2 'f:s1)
  (scheme#list))

;; END OF FILE
