;;;; square-functor.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##core#begin
  (##sys#register-functor
    (##core#quote square-functor)
    (##core#quote ((M *)))
    (##core#quote *)
    (##core#quote ((import scheme M) (define (square x) (* x x))))))
(##sys#register-compiled-module
  'square-functor
  'square-functor
  (scheme#list)
  '()
  (scheme#list)
  (scheme#list))

;; END OF FILE
