;;;; m3.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import scheme m2))
(##sys#register-compiled-module
  'm3
  (list)
  '()
  (list (cons 's3 (syntax-rules () ((_) (s2)))))
  (list))

;; END OF FILE
