;;;; reexport-m5.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import scheme))
(##sys#register-compiled-module
  'reexport-m5
  (list)
  '()
  (list (cons 's2 (syntax-rules () ((_) (display 1))))
        (cons 's1 (syntax-rules () ((_) (s2)))))
  (list))

;; END OF FILE
