;;;; reexport-m6.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import (prefix reexport-m5 f:)))
(##sys#register-compiled-module
  'reexport-m6
  (list)
  '()
  (list 'f:s2 'f:s1)
  (list))

;; END OF FILE
