;;;; reexport-m3.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import chicken scheme))
(##sys#register-compiled-module
  'reexport-m3
  (list '(bar . reexport-m3#bar))
  '()
  (list (cons 'foo (ir-macro-transformer (lambda (e i c) `(bar)))))
  (list))

;; END OF FILE
