;;;; reexport-m4.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import chicken scheme reexport-m3 reexport-m3))
(##sys#register-compiled-module
  'reexport-m4
  (list '(bar . reexport-m3#bar))
  '()
  (list (cons 'baz (ir-macro-transformer (lambda (e i c) `(foo)))) 'foo 'foo)
  (list))

;; END OF FILE
