;;;; square-functor.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import scheme chicken))
(##core#begin
  (##sys#register-functor
    'square-functor
    '((M *))
    '*
    '((import scheme M) (define (square x) (* x x)))))
(##sys#register-compiled-module 'square-functor (list) '() (list) (list))

;; END OF FILE
