;;;; bind-translator.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'bind-translator
  'bind-translator
  (scheme#list)
  '((parse-easy-ffi . bind-translator#parse-easy-ffi)
    (register-ffi-macro . bind-translator#register-ffi-macro)
    (ffi-include-path-list . bind-translator#ffi-include-path-list)
    (ffi-dont-include . bind-translator#ffi-dont-include)
    (foreign-type-declaration . bind-translator#foreign-type-declaration)
    (parse-type-declaration . bind-translator#parse-type-declaration)
    (parse-opaque-type-declaration
      .
      bind-translator#parse-opaque-type-declaration)
    (check-c-syntax . bind-translator#check-c-syntax)
    (set-bind-options . bind-translator#set-bind-options)
    (set-renaming . bind-translator#set-renaming)
    (no-c-syntax-checks . bind-translator#no-c-syntax-checks)
    (debugging-chicken . bind-translator#debugging-chicken)
    (test-debug-flag . bind-translator#test-debug-flag)
    (bind-foreign-lambda* . bind-translator#bind-foreign-lambda*))
  (scheme#list)
  (scheme#list))

;; END OF FILE
