;;;; cplusplus-object.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'cplusplus-object
  'cplusplus-object
  (scheme#list)
  '((<c++-object> . cplusplus-object#<c++-object>)
    (new . cplusplus-object#new)
    (delete . cplusplus-object#delete)
    (constructor . cplusplus-object#constructor)
    (destructor . cplusplus-object#destructor))
  (scheme#list)
  (scheme#list))

;; END OF FILE
