;;;; chicken.compiler.c-backend.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'chicken.compiler.c-backend
  'c-backend
  (scheme#list)
  '((generate-code . chicken.compiler.c-backend#generate-code)
    (foreign-type-declaration
      .
      chicken.compiler.c-backend#foreign-type-declaration))
  (scheme#list)
  (scheme#list))

;; END OF FILE
