;;;; chicken.format.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'chicken.format
  'extras
  (scheme#list)
  '((format . chicken.format#format)
    (fprintf . chicken.format#fprintf)
    (printf . chicken.format#printf)
    (sprintf . chicken.format#sprintf))
  (scheme#list)
  (scheme#list))

;; END OF FILE
