;;;; chicken.compiler.lfa2.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'chicken.compiler.lfa2
  'lfa2
  (scheme#list)
  '((perform-secondary-flow-analysis
      .
      chicken.compiler.lfa2#perform-secondary-flow-analysis))
  (scheme#list)
  (scheme#list))

;; END OF FILE
