;;;; chicken.compiler.compiler-syntax.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'chicken.compiler.compiler-syntax
  'compiler-syntax
  (scheme#list)
  '((compiler-syntax-statistics
      .
      chicken.compiler.compiler-syntax#compiler-syntax-statistics))
  (scheme#list)
  (scheme#list))

;; END OF FILE
