#!/usr/bin/env python

from rsa import *
from rsa.bigfile import * #won't be around forever
import sys

if len(sys.argv) != 3 :
     print("include two path names")
     exit()

# input
privKeyLocation = "/home/jordan/privateKey" #"/home/jordan/privateKey"
inputfile = sys.argv[1]
outputfile = sys.argv[2]

# state changes
privkeyfile = open(privKeyLocation, 'r')
priv_key = eval(privkeyfile.read())

with open(inputfile, 'rb') as infile, open(outputfile, 'wb') as outfile:
     decrypt_bigfile(infile, outfile, priv_key)

