#!/usr/bin/env python

from rsa import *
from rsa.bigfile import * #won't be around forever
import sys

if len(sys.argv) != 3 :
     print("include two path names")
     exit()

# input 
pubKeyLocation = "/home/jordan/publicKey" #file could also be in drive32
inputfile = sys.argv[1]
outputfile = sys.argv[2]

# state changes
pubkeyfile = open(pubKeyLocation, 'r')
pub_key = eval(pubkeyfile.read())

with open(inputfile, 'rb') as infile, open(outputfile, 'wb') as outfile:
   encrypt_bigfile(infile, outfile, pub_key)
