#!/bin/bash



# if [$# -ne 1]; then #-ne for != does not work!!!
#   echo "getPassword [name of place with password]"
#   exit 0
# fi

decrypt ~/encryptedPasswords ~/.myTempFile

#change -A 2 to "until reach certain char"?
grep -i -A 2 $1 ~/.myTempFile 

shred ~/.myTempFile
rm ~/.myTempFile
