#!/bin/bash


echo "put: copy file from computer to server"
echo "get: copy server file to computer"

if [ "$1" ]; then
    if (($1 <= 9)); then
        sftp jomawink@cs0$1.cs.iusb.edu 
    fi
else 
   sftp jomawink@cs05.cs.iusb.edu 
fi

# ftp commands
# put: copy file from computer to server
# get: copy server file to computer

# means server is busy or whatever
error= "ssh_exchange_identification: read: Connection reset by peer"
