;;;; reverser.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import scheme chicken srfi-13))
(##sys#register-compiled-module
  'reverser
  (list)
  '((rev . reverser#rev) (rev-version . reverser#rev-version))
  (list)
  (list))

;; END OF FILE
