;;;; reverser.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'reverser
  'reverser
  (scheme#list)
  '((rev . reverser#rev)
    (string-reverse . reverser#string-reverse)
    (rev-version . reverser#rev-version))
  (scheme#list)
  (scheme#list))

;; END OF FILE
