;;;; sample-module.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'sample-module
  'sample-module
  (scheme#list)
  '((foo . sample-module#foo))
  (scheme#list)
  (scheme#list))

;; END OF FILE
