#!/bin/bash

# to make a library for guile, undocumented

filename=$1
program=${filename:0:-2} #to remove the .c

functionWant=$2

# compile to shared guile library
gcc `pkg-config --cflags guile-2.0` \
   -shared -o ~/Backup/nonsensitive/programs/guile/$program.so -fPIC $program.c

# move a copy of source file to library
cp $program.c ~/Backup/nonsensitive/programs/guile/

# if second arg exists do this
if [ $# -eq 2 ]; then
    echo "(load-extension "\"$program\"" "\"$functionWant\"")" >> ~/.guile
fi
